// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0s9wMesEkVwWZ8cfxfC2_QBRsZmcuxxI',
    appId: '1:412607044488:web:994becdc7eeec243b9383d',
    messagingSenderId: '412607044488',
    projectId: 'krishi-sankalp',
    authDomain: 'krishi-sankalp.firebaseapp.com',
    storageBucket: 'krishi-sankalp.appspot.com',
    measurementId: 'G-1H8Q4TG3QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeil9p0WMpYLczAMkwU0S6-uQ7y-W4tec',
    appId: '1:412607044488:android:30a6437f34ca6ecdb9383d',
    messagingSenderId: '412607044488',
    projectId: 'krishi-sankalp',
    storageBucket: 'krishi-sankalp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzb4XzBSzgddeDoA7y4BHGEofg1ftGmxA',
    appId: '1:412607044488:ios:4fc4db8e0b70b5f1b9383d',
    messagingSenderId: '412607044488',
    projectId: 'krishi-sankalp',
    storageBucket: 'krishi-sankalp.appspot.com',
    iosClientId: '412607044488-dp3ka58d1asrm9bcv39k8pmdpa03nl5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.krishiSankalp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzb4XzBSzgddeDoA7y4BHGEofg1ftGmxA',
    appId: '1:412607044488:ios:d28e60aff61957d6b9383d',
    messagingSenderId: '412607044488',
    projectId: 'krishi-sankalp',
    storageBucket: 'krishi-sankalp.appspot.com',
    iosClientId: '412607044488-7e1adibvhp7seu2e77j8ocmcvvusvbmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.krishiSankalp.RunnerTests',
  );
}
